"""add background jobs table

Revision ID: bg_jobs_001
Revises: 
Create Date: 2024-12-04 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bg_jobs_001'
down_revision = None  # Update this to the latest revision
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('progress_message', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for performance
    op.create_index('ix_background_jobs_status', 'background_jobs', ['status'])
    op.create_index('ix_background_jobs_created_at', 'background_jobs', ['created_at'])
    op.create_index('ix_background_jobs_session_id', 'background_jobs', ['session_id'])
    op.create_index('ix_background_jobs_user_id', 'background_jobs', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_background_jobs_user_id', table_name='background_jobs')
    op.drop_index('ix_background_jobs_session_id', table_name='background_jobs')
    op.drop_index('ix_background_jobs_created_at', table_name='background_jobs')
    op.drop_index('ix_background_jobs_status', table_name='background_jobs')
    op.drop_table('background_jobs')
    # ### end Alembic commands ###