name: EAS Build and Submit

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - run: cd driver-app && eas build --platform ios --profile production --non-interactive
      - run: cd driver-app && eas build --platform android --profile production --non-interactive
      - run: cd driver-app && eas submit --platform ios --profile production --latest --non-interactive
      - run: cd driver-app && eas submit --platform android --profile production --latest --non-interactive
