name: Android Release APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'driver-app/**'

jobs:
  android-apk:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: driver-app
    env:
      EXPO_NO_TELEMETRY: 1
      CI: 1
      # Expose ONLY the five secrets to the app/config
      API_BASE: ${{ secrets.API_BASE }}
      FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install npm deps
        run: npm ci

      - name: Prebuild (clean)
        run: |
          npm run clean:android || true
          npm run prebuild:android

      - name: Patch Android Gradle properties (1st pass)
        run: node scripts/ci/patch-android-gradle.js || true

      - name: Write google-services.json from secret
        run: node scripts/ci/write-google-services-json.js

      - name: Validate google-services package name
        run: node scripts/ci/validate-package.js

      - name: Patch Android Gradle properties (2nd pass)
        run: node scripts/ci/patch-android-gradle.js || true

      - name: Build APK
        run: |
          cd android
          ./gradlew --no-daemon clean :app:assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: driver-release-apk
          path: driver-app/android/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
