name: Android Release APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ "driver-app/**" ]
jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: driver-app
    env:
      API_BASE: ${{ secrets.API_BASE }}
      FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Materialize google-services.json
        run: |
          printf "%s" "$GOOGLE_SERVICES_JSON" > google-services.json
          test -s google-services.json
      - name: Create local.properties
        run: |
          echo API_BASE=$API_BASE >> local.properties
      - name: Build (release)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9
          arguments: ":app:assembleRelease"
      - uses: actions/upload-artifact@v4
        with:
          name: driver-app-release-apk
          path: driver-app/app/build/outputs/apk/release/*.apk
