name: Android APK (Driver App)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: driver-app
    env:
      EXPO_NO_TELEMETRY: 1
      NODE_ENV: production
      CI: true
      API_BASE: ${{ secrets.API_BASE }}
      FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: |
            driver-app/yarn.lock
            driver-app/package.json

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Write google-services.json from secret
        working-directory: .
        run: node driver-app/scripts/ci/write-google-services-json.js

      - name: Validate google-services package name
        working-directory: .
        run: node driver-app/scripts/ci/validate-package.js

      - name: Prebuild (Android)
        run: yarn ci:prebuild:android

      - name: Patch Gradle for Kotlin/Java alignment
        working-directory: .
        run: node driver-app/scripts/ci/patch-gradle.js

      - name: Bundle JS (Hermes)
        run: yarn ci:bundle:android

      - name: Assemble APK
        run: yarn ci:assemble:android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: driver-app-release-apk
          path: driver-app/android/app/build/outputs/apk/release/app-release.apk
