name: driver-app-ci

on:
  push:
    paths:
      - 'driver-app/**'
      - '.github/workflows/driver-app-ci.yml'
  pull_request:
    paths:
      - 'driver-app/**'
      - '.github/workflows/driver-app-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStore=$JAVA_HOME/lib/security/cacerts -Djavax.net.ssl.trustStoreType=JKS
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2g"
    defaults:
      run:
        working-directory: driver-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: driver-app/package-lock.json
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: java -version && keytool -list -cacerts | head -n 5
      - run: npm ci
      - run: npm run typecheck
      - run: npm test
