name: Build Driver Android (Debug)

on:
  workflow_dispatch:
  push:
    paths:
      - 'driver-app/**'
      - '.github/workflows/driver-android-debug.yml'

jobs:
  build-android-debug:
    runs-on: ubuntu-latest
    env:
      API_BASE: https://orderops-api-v1.onrender.com   # 👈 set your backend URL here
      EXPO_NO_TELEMETRY: 1
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # ── If you DON'T want to commit google-services.json, uncomment the next step
      #    and add a repo secret named GOOGLE_SERVICES_JSON (content of the file).
      # - name: Write google-services.json from secret
      #   run: |
      #     mkdir -p driver-app
      #     echo "$GOOGLE_SERVICES_JSON" > driver-app/google-services.json
      #   env:
      #     GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Install JS deps
        working-directory: driver-app
        run: npm ci

      - name: Prebuild native Android project
        working-directory: driver-app
        run: npx expo prebuild --platform android --non-interactive

      - name: Make gradlew executable
        working-directory: driver-app/android
        run: chmod +x ./gradlew

      - name: Build debug APK
        working-directory: driver-app/android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: driver-app-debug-apk
          path: driver-app/android/app/build/outputs/apk/debug/app-debug.apk
