name: Firebase App Distribution

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ "driver-app/**" ]

jobs:
  distribute:
    runs-on: ubuntu-22.04
    env:
      API_BASE: ${{ secrets.API_BASE }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Materialize google-services.json
        working-directory: driver-app
        run: |
          mkdir -p app
          printf "%s" "$GOOGLE_SERVICES_JSON" > app/google-services.json

      - name: Create local.properties
        working-directory: driver-app
        run: echo API_BASE=$API_BASE >> local.properties

      - name: Build Debug APK for distribution
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9
          build-root-directory: driver-app
          arguments: ":app:assembleDebug"

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          groups: testers
          releaseNotes: |
            Build ${{ github.run_number }}
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref_name }}
          file: driver-app/app/build/outputs/apk/debug/app-debug.apk
