name: Generate Keystore (One-time use)

on:
  workflow_dispatch:
    inputs:
      keystore_password:
        description: 'Keystore password'
        required: true
        type: string
      key_alias:
        description: 'Key alias name'
        required: true
        default: 'orderops-driver'
      organization:
        description: 'Organization name'
        required: true
        default: 'OrderOps'

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Generate Keystore
      run: |
        keytool -genkeypair -v \
          -keystore keystore.jks \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -alias ${{ inputs.key_alias }} \
          -dname "CN=${{ inputs.organization }}, OU=Mobile, O=${{ inputs.organization }}, L=City, S=State, C=US" \
          -storepass ${{ inputs.keystore_password }} \
          -keypass ${{ inputs.keystore_password }}
    
    - name: Encode Keystore to Base64
      run: |
        base64 -w 0 keystore.jks > keystore_base64.txt
        echo "=== COPY THIS TO GITHUB SECRET 'KEYSTORE_FILE' ==="
        cat keystore_base64.txt
        echo ""
        echo "=== END OF BASE64 KEYSTORE ==="
    
    - name: Upload Keystore Files
      uses: actions/upload-artifact@v4
      with:
        name: keystore-files
        path: |
          keystore.jks
          keystore_base64.txt