name: Build Android Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_NO_TELEMETRY: 1
      CI: true
      # Make ONLY the five secrets available to the build
      API_BASE: ${{ secrets.API_BASE }}
      FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
    defaults:
      run:
        working-directory: driver-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: driver-app/package-lock.json
      - name: Install dependencies (include dev deps)
        env:
          NODE_ENV: ""
        run: npm ci --include=dev
      - name: Expo sanity check
        run: npx expo doctor || true
      - name: Create google-services.json from secret (RAW JSON, not base64)
        run: |
          if [ -z "${GOOGLE_SERVICES_JSON:-}" ]; then
            echo "ERROR: Missing GOOGLE_SERVICES_JSON secret"; exit 1
          fi
          VAL="${GOOGLE_SERVICES_JSON}"
          case "$VAL" in
            \"*) VAL="${VAL%\"}"; VAL="${VAL#\"}";;
            \'*) VAL="${VAL%\'}"; VAL="${VAL#\'}";;
          esac
          mkdir -p android/app
          printf "%s" "$VAL" > android/app/google-services.json
          test -s android/app/google-services.json || { echo "ERROR: google-services.json empty"; exit 1; }
      - name: Prebuild Android project
        run: npx expo prebuild --platform android --clean
      - name: Ensure android project generated
        run: test -d android && test -f android/gradlew
      - name: Set Kotlin/JVM compiler target and Gradle memory (post-prebuild)
        run: |
          {
            echo "kotlin.jvm.target=17"
            if ! grep -q "^org\.gradle\.jvmargs=" android/gradle.properties; then
              echo "org.gradle.jvmargs=-Xmx4096m -Dkotlin.daemon.jvm.options=-Xmx2048m"
            fi
          } >> android/gradle.properties
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
          cache-dependency-path: driver-app/android/gradle/wrapper/gradle-wrapper.properties
      - name: Build release APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew --no-daemon --stacktrace --info assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: driver-app/android/app/build/outputs/apk/release/*.apk
