name: Build Android Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_NO_TELEMETRY: 1
      NODE_ENV: production
      CI: true
      API_BASE: ${{ secrets.API_BASE }}
      FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
    defaults:
      run:
        working-directory: driver-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: driver-app/package-lock.json
      - name: Create google-services.json from secret (RAW JSON, not base64)
        run: |
          if [ -z "${GOOGLE_SERVICES_JSON}" ]; then
            echo "ERROR: Missing GOOGLE_SERVICES_JSON secret"; exit 1
          fi
          VAL="${GOOGLE_SERVICES_JSON}"
          case "$VAL" in
            \"*) VAL="${VAL%\"}"; VAL="${VAL#\"}";;
            \'*) VAL="${VAL%\'}"; VAL="${VAL#\'}";;
          esac
          printf "%s" "$VAL" > google-services.json
          test -s google-services.json || { echo "ERROR: google-services.json empty"; exit 1; }
      - name: Pre-bundle diagnostics
        run: |
          node -v
          yarn -v || echo "Yarn not installed"
          npm -v
          if [ -n "$API_BASE" ]; then echo "API_BASE is set"; else echo "API_BASE is not set"; fi
      - name: Install dependencies
        run: npm ci

      - name: Prebuild Android project
        run: npx expo prebuild --platform android --non-interactive --clean

      - name: Ensure android project generated
        run: test -d android && test -f android/gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
          cache-dependency-path: driver-app/android/gradle/wrapper/gradle-wrapper.properties

      - name: Build release APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew --no-daemon --stacktrace --info assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: driver-app/android/app/build/outputs/apk/release/*.apk
