name: Build Android Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_BASE: ${{ secrets.API_BASE }}
    defaults:
      run:
        working-directory: driver-app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: driver-app/package-lock.json
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - name: Diagnostics
        run: |
          java -version
          keytool -list -cacerts | head -n 20
      - name: Install dependencies
        run: npm ci
      - name: Prebuild Android project
        run: npx expo prebuild --platform android --non-interactive --clean
      - name: Set up google-services.json
        if: ${{ secrets.GOOGLE_SERVICES_JSON != '' }}
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
      - name: Ensure android project generated
        run: test -d android || exit 1
      - name: Build release APK
        working-directory: android
        run: ./gradlew assembleRelease
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/*.apk
